services:
  api_template:
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile
    container_name: api_template
    image: api_template:latest
    ports:
      - 8000:8000
    env_file:
      - ../.env
    networks:
      tsp-net:
        ipv4_address: 192.168.10.1

networks:
  tsp-net:
    # driver: bridge
    name: tsp-net-1
    external: true
